name: firestore_data_table_source
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
